name: Supa-backup-to-R2

on:
  workflow_dispatch: # Manuel çalıştırmaya izin verir
  schedule:
    - cron: '0 20 * * *'

permissions:
  contents: read # Repo içeriğini okumak için yeterli

jobs:
  run_db_backup:
    runs-on: ubuntu-latest
    env:
      supabase_db_url: ${{ secrets.SUPABASE_DB_URL }}
      # R2 bağlantısı için gerekli AWS CLI değişkenleri
      AWS_ACCESS_KEY_ID: ${{ secrets.CF_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.CF_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Create and compress backup
        id: compress_backup
        run: |
          # Geçici klasör oluştur
          mkdir -p ./supabase_backups

          # Veritabanı bileşenlerini dışa aktar
          supabase db dump --db-url "$supabase_db_url" -f ./supabase_backups/roles.sql --role-only
          supabase db dump --db-url "$supabase_db_url" -f ./supabase_backups/schema.sql
          supabase db dump --db-url "$supabase_db_url" -f ./supabase_backups/data.sql --data-only --use-copy
          
          # Tarih içeren dosya adı oluştur
          FILE_NAME="backup-$(date +%Y-%m-%d).zip"
          
          # Dosyaları ziple
          zip -r "${FILE_NAME}" ./supabase_backups
          
          # Dosya adını bir sonraki adımda kullanmak için çıktı olarak kaydet
          echo "file_name=${FILE_NAME}" >> $GITHUB_OUTPUT

      - name: Upload to Cloudflare R2
        run: |
          # AWS CLI kullanarak R2 bucket'ına yükle
          aws s3 cp \
            "${{ steps.compress_backup.outputs.file_name }}" \
            "s3://${{ secrets.CF_BUCKET_NAME }}/${{ steps.compress_backup.outputs.file_name }}" \
            --endpoint-url "${{ secrets.CF_BUCKET_ENDPOINT }}"
